### PR TITLE
Port scope and acquisition visualisation for Qblox

### PR DESCRIPTION
**Pull request by hamidelmaazouz**
- Helps a lot in debugging
- Plots just the pulse timeline, no awareness of control flow (equivalent to a single sweep point and a single shot).
- Any desired transforms to the I and Q signals can be added later on in another sweep
- Some cleanups

Note:
- Realtime plotting that is control flow aware can be done via walking the program and accumulating updates to the timeline array, but this is enough for now

### CODE REVIEW

**Comment by daria-oqc** [comment]
Looks good, maybe it would be helpful to create an example notebook that shows the functionalities of the plot_packages and plot_acquisitions methods?

**Review by daria-oqc — APPROVED** [review]

**Review by bgsach — APPROVED** [review]
LGTM

**Review by lcauser-oqc — APPROVED** [review]
lgtm

**Comment by hamidelmaazouz** [comment]
> Looks good, maybe it would be helpful to create an example notebook that shows the functionalities of the plot_packages and plot_acquisitions methods?

uses and examples of these things are in another corner of the codebase and notebooks are not supposed to end up here, but can share internally

**Pull request merged**
