### PR TITLE
The qutip warnings should now be fixed.

### PR DESCRIPTION
**Pull request by lcauser**
The Options() class that qutip provides to its dynamical solvers is now deprecated and is replaced by a dictionary.

### CODE REVIEW

**Comment by lcauser** [comment]
have read the Contributor License Agreement and I hereby accept the Terms.

**Comment by lcauser** [comment]
recheck

**Review by bgsach — APPROVED** [review]
Looks good to me

**Review by hamidelmaazouz — APPROVED** [review]

**Review by hamidelmaazouz — APPROVED** [review]
Deprecation warning:
```
 tests/qat/test_qasm.py::TestQiskitBackend::test_simple_circuit
  /Users/runner/work/qat/qat/src/qat/purr/integrations/qiskit.py:80: DeprecationWarning: The function ``qiskit.compiler.assembler.assemble()`` is deprecated as of qiskit 1.2. It will be removed in the 2.0 release. The `Qobj` class and related functionality are part of the deprecated `BackendV1` workflow,  and no longer necessary for `BackendV2`. If a user workflow requires `Qobj` it likely relies on deprecated functionality and should be updated to use `BackendV2`.
    assembled_data = assemble(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

Intermittent test failure. This is already known, so I wouldn't worry about it just now.

```
FAILED tests/qat/test_readout_mitigation.py::TestOnNoisySimulator::test_prepare_bitstring_and_measure[11] - assert np.float64(0.05127999999999994) < 0.051
 +  where np.float64(0.05127999999999994) = abs(np.float64(0.05127999999999994))
====== 1 failed, 547 passed, 51 skipped, 3 warnings in 116.73s (0:01:56) =======
Error: Process completed with exit code 1.
```

Reason has to do with numpy randomness and how the noisy backend is setup. It can be addressed in a subsequent fix.

**Pull request merged**
