### PR TITLE
Bring back cached properties

### PR DESCRIPTION
**Pull request by hamidelmaazouz**

### CODE REVIEW

**Review by daria-oqc — APPROVED** [review]
👍🏻

**Review by lcauser-oqc — APPROVED** [review]
looks good to me

**Comment by bread-oqc** [comment]
This is a breaking change for dependent components. To avoid the breaking change, we could cache and return a lambda so that the expression '*.full_id' is still callable but this is grosssss.

I reckon this is the 'correct' solution.

**Comment by bgsach** [comment]
There are concerns from Kajsa about mutability here. We should pause and have a think.

**Comment by hamidelmaazouz** [comment]
> There are concerns from Kajsa about mutability here. We should pause and have a think.

@keriksson-rosenqvist could you share where the mutability requirement comes from ?

**Pull request closed without merging**
