### PR TITLE
added aphinx pages for github actions

### PR DESCRIPTION
**Pull request by ruqaiyah-oqc**
- please note that the sphinx build being used is sphinx-multiversion
- a branch is open that will be where the sphinx docs that are built will be held (gh-pages) with file structure
- added the sphinx multiversion to the pyproject.toml
- added link to readme and pyproject.toml
- fixed image on readme.rst

### CODE REVIEW

**Comment by ruqaiyah-oqc** [comment]
I have read the Contributor License Agreement and I hereby accept the Terms.

**Review by jfriel-oqc — APPROVED** [review]

**Comment by jfriel-oqc** [comment]
where do these get published to? Would be great to check that out, approving to not block the infrastructure of all this. As soon as you're happy merge away as far as I'm concerned :ok_hand:

**Comment by ruqaiyah-oqc** [comment]
> where do these get published to? Would be great to check that out, approving to not block the infrastructure of all this. As soon as you're happy merge away as far as I'm concerned 👌

It will be at https://oqc-community.github.io/qat - just added it to the readme and pyproject.toml

Once pushed to main we will be able to see this in action

**Comment by keriksson-rosenqvist** [comment]
A few comments on the outputted pages:
* The actual QAT docs seem to be missing from 1.0.0
* No main branch version
* The branch version says "QAT 1.0.0 documentation" at the top, should ideally be changed to the branch name, unless that line can be removed from all versions.

**Review by keriksson-rosenqvist — APPROVED** [review]

**Comment by ruqaiyah-oqc** [comment]
> A few comments on the outputted pages:
> 
>     * The actual QAT docs seem to be missing from 1.0.0
> 
>     * No main branch version
> 
>     * The branch version says "QAT 1.0.0 documentation" at the top, should ideally be changed to the branch name, unless that line can be removed from all versions.

Resolved all, main docs will become available once this is pushed to main. All future versions will not have the line "QAT 1.0.0 documentation"

**Pull request merged**
